# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/pythonProjects/pyqt5_practice/ImControls.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSetBrightness = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetBrightness.setGeometry(QtCore.QRect(330, 10, 191, 41))
        self.btnSetBrightness.setObjectName("btnSetBrightness")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 150, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tbBrightness = QtWidgets.QLineEdit(self.centralwidget)
        self.tbBrightness.setGeometry(QtCore.QRect(160, 10, 161, 31))
        self.tbBrightness.setObjectName("tbBrightness")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 150, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tbDistance = QtWidgets.QLineEdit(self.centralwidget)
        self.tbDistance.setGeometry(QtCore.QRect(160, 50, 161, 31))
        self.tbDistance.setObjectName("tbDistance")
        self.btnGray = QtWidgets.QPushButton(self.centralwidget)
        self.btnGray.setGeometry(QtCore.QRect(10, 90, 162, 35))
        self.btnGray.setObjectName("btnGray")
        self.btnHSV = QtWidgets.QPushButton(self.centralwidget)
        self.btnHSV.setGeometry(QtCore.QRect(180, 90, 162, 35))
        self.btnHSV.setObjectName("btnHSV")
        self.btnCartoon = QtWidgets.QPushButton(self.centralwidget)
        self.btnCartoon.setGeometry(QtCore.QRect(520, 90, 162, 35))
        self.btnCartoon.setObjectName("btnCartoon")
        self.btnCanny = QtWidgets.QPushButton(self.centralwidget)
        self.btnCanny.setGeometry(QtCore.QRect(350, 90, 162, 35))
        self.btnCanny.setObjectName("btnCanny")
        self.btnPencil = QtWidgets.QPushButton(self.centralwidget)
        self.btnPencil.setGeometry(QtCore.QRect(180, 130, 162, 35))
        self.btnPencil.setObjectName("btnPencil")
        self.btnWarm = QtWidgets.QPushButton(self.centralwidget)
        self.btnWarm.setGeometry(QtCore.QRect(350, 130, 162, 35))
        self.btnWarm.setObjectName("btnWarm")
        self.btnCool = QtWidgets.QPushButton(self.centralwidget)
        self.btnCool.setGeometry(QtCore.QRect(520, 130, 162, 35))
        self.btnCool.setObjectName("btnCool")
        self.btnHLS = QtWidgets.QPushButton(self.centralwidget)
        self.btnHLS.setGeometry(QtCore.QRect(10, 130, 162, 35))
        self.btnHLS.setObjectName("btnHLS")
        self.btnMirror1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMirror1.setGeometry(QtCore.QRect(180, 170, 162, 35))
        self.btnMirror1.setObjectName("btnMirror1")
        self.btnMirror2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMirror2.setGeometry(QtCore.QRect(350, 170, 162, 35))
        self.btnMirror2.setObjectName("btnMirror2")
        self.btnDistancePreview = QtWidgets.QPushButton(self.centralwidget)
        self.btnDistancePreview.setGeometry(QtCore.QRect(520, 210, 162, 35))
        self.btnDistancePreview.setObjectName("btnDistancePreview")
        self.btnFindSquares = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindSquares.setGeometry(QtCore.QRect(10, 170, 162, 35))
        self.btnFindSquares.setObjectName("btnFindSquares")
        self.btnMirror5 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMirror5.setGeometry(QtCore.QRect(180, 210, 162, 35))
        self.btnMirror5.setObjectName("btnMirror5")
        self.btnMirror4 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMirror4.setGeometry(QtCore.QRect(10, 210, 162, 35))
        self.btnMirror4.setObjectName("btnMirror4")
        self.btnMirror3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnMirror3.setGeometry(QtCore.QRect(520, 170, 162, 35))
        self.btnMirror3.setObjectName("btnMirror3")
        self.btnDistance = QtWidgets.QPushButton(self.centralwidget)
        self.btnDistance.setGeometry(QtCore.QRect(350, 210, 162, 35))
        self.btnDistance.setObjectName("btnDistance")
        self.btnLaplace = QtWidgets.QPushButton(self.centralwidget)
        self.btnLaplace.setGeometry(QtCore.QRect(180, 250, 162, 35))
        self.btnLaplace.setObjectName("btnLaplace")
        self.btnXYZ = QtWidgets.QPushButton(self.centralwidget)
        self.btnXYZ.setGeometry(QtCore.QRect(350, 250, 162, 35))
        self.btnXYZ.setObjectName("btnXYZ")
        self.btnNoFilter = QtWidgets.QPushButton(self.centralwidget)
        self.btnNoFilter.setGeometry(QtCore.QRect(520, 250, 162, 35))
        self.btnNoFilter.setObjectName("btnNoFilter")
        self.btnNegative = QtWidgets.QPushButton(self.centralwidget)
        self.btnNegative.setGeometry(QtCore.QRect(10, 250, 162, 35))
        self.btnNegative.setObjectName("btnNegative")
        self.btnCW = QtWidgets.QPushButton(self.centralwidget)
        self.btnCW.setGeometry(QtCore.QRect(10, 290, 331, 35))
        self.btnCW.setObjectName("btnCW")
        self.btnCCW = QtWidgets.QPushButton(self.centralwidget)
        self.btnCCW.setGeometry(QtCore.QRect(350, 290, 331, 35))
        self.btnCCW.setObjectName("btnCCW")
        self.btnStartStop = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartStop.setGeometry(QtCore.QRect(10, 330, 215, 35))
        self.btnStartStop.setObjectName("btnStartStop")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(230, 330, 222, 35))
        self.btnSave.setObjectName("btnSave")
        self.btnQuit = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuit.setGeometry(QtCore.QRect(460, 330, 220, 35))
        self.btnQuit.setObjectName("btnQuit")
        self.tbFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.tbFileName.setGeometry(QtCore.QRect(230, 370, 221, 38))
        self.tbFileName.setObjectName("tbFileName")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 370, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lbPicture = QtWidgets.QLabel(self.centralwidget)
        self.lbPicture.setGeometry(QtCore.QRect(10, 420, 90, 28))
        self.lbPicture.setObjectName("lbPicture")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 708, 34))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Graph = QtWidgets.QAction(MainWindow)
        self.actionOpen_Graph.setObjectName("actionOpen_Graph")
        self.actionClose_Graph = QtWidgets.QAction(MainWindow)
        self.actionClose_Graph.setObjectName("actionClose_Graph")
        self.actionPause_Graph = QtWidgets.QAction(MainWindow)
        self.actionPause_Graph.setObjectName("actionPause_Graph")
        self.menuFile.addAction(self.actionOpen_Graph)
        self.menuFile.addAction(self.actionPause_Graph)
        self.menuFile.addAction(self.actionClose_Graph)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSetBrightness.setText(_translate("MainWindow", "Set Brightness"))
        self.label.setText(_translate("MainWindow", "Brightness"))
        self.label_2.setText(_translate("MainWindow", "Distance"))
        self.btnGray.setText(_translate("MainWindow", "gray"))
        self.btnHSV.setText(_translate("MainWindow", "HSV"))
        self.btnCartoon.setText(_translate("MainWindow", "Cartoon"))
        self.btnCanny.setText(_translate("MainWindow", "Canny"))
        self.btnPencil.setText(_translate("MainWindow", "Pencil"))
        self.btnWarm.setText(_translate("MainWindow", "Warming"))
        self.btnCool.setText(_translate("MainWindow", "Cooling"))
        self.btnHLS.setText(_translate("MainWindow", "HLS"))
        self.btnMirror1.setText(_translate("MainWindow", "mirror 1"))
        self.btnMirror2.setText(_translate("MainWindow", "mirror 2"))
        self.btnDistancePreview.setText(_translate("MainWindow", "distance preview"))
        self.btnFindSquares.setText(_translate("MainWindow", "Find Squares"))
        self.btnMirror5.setText(_translate("MainWindow", "Mirror 5"))
        self.btnMirror4.setText(_translate("MainWindow", "Mirror 4"))
        self.btnMirror3.setText(_translate("MainWindow", "Mirror 3"))
        self.btnDistance.setText(_translate("MainWindow", "Distances"))
        self.btnLaplace.setText(_translate("MainWindow", "laplace"))
        self.btnXYZ.setText(_translate("MainWindow", "xyz"))
        self.btnNoFilter.setText(_translate("MainWindow", "No Filter"))
        self.btnNegative.setText(_translate("MainWindow", "Negative"))
        self.btnCW.setText(_translate("MainWindow", "CW"))
        self.btnCCW.setText(_translate("MainWindow", "CCW"))
        self.btnStartStop.setText(_translate("MainWindow", "Start"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))
        self.label_3.setText(_translate("MainWindow", "FileName"))
        self.lbPicture.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Graph.setText(_translate("MainWindow", "Open Graph"))
        self.actionClose_Graph.setText(_translate("MainWindow", "Close Graph"))
        self.actionPause_Graph.setText(_translate("MainWindow", "Pause Graph"))

